### ISSUE TITLE
inteltau.set_subsets_splits() ---->> with open(file, "r") as f:---->>FileNotFoundError: [Errno 2] No such file or directory: 'D:/processed_1080p/splits//Intel-TAU_v3_filelist_subset01.txt'

### ISSUE THREAD

**Issue by ToChangeBetter** [firasl/CWCC#5]
Can you help me? I can't find the reason.

**Comment by firasl** [comment]
Hi, That means you don't have the split files. Download them from the dataset webpage. 
In general, try to follow the download steps in the dataset webpage to avoid errors.

**Comment by ToChangeBetter** [comment]
&nbsp;Do you have the WeChat? We can communicate with WeChat. Thanks you very much!!!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "firasl/CWCC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 晚上7:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [firasl/CWCC] inteltau.set_subsets_splits() ----&gt;&gt; with open(file, "r") as f:----&gt;&gt;FileNotFoundError: [Errno 2] No such file or directory: 'D:/processed_1080p/splits//Intel-TAU_v3_filelist_subset01.txt' (Issue #5)





 
Hi, That means you don't have the split files. Download them from the dataset webpage.
 In general, try to follow the download steps in the dataset webpage to avoid errors.

**Comment by ToChangeBetter** [comment]
I think that your paper is excellent ！ I want to reproduce your paper , But I meet many bug.Can you help me ?
Can&nbsp; we&nbsp; be friend?&nbsp; Do you have WeChat ?&nbsp; Can&nbsp; we add a the tool of chat?
Thanks!
Yang.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "firasl/CWCC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 晚上7:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [firasl/CWCC] inteltau.set_subsets_splits() ----&gt;&gt; with open(file, "r") as f:----&gt;&gt;FileNotFoundError: [Errno 2] No such file or directory: 'D:/processed_1080p/splits//Intel-TAU_v3_filelist_subset01.txt' (Issue #5)





 
Closed #5.
